# Generated by Django 4.2.5 on 2024-03-12 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapi', '0002_buscategory_busowner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buscategory',
            name='busowner',
        ),
        migrations.RemoveField(
            model_name='buscategory',
            name='type',
        ),
        migrations.AddField(
            model_name='buscategory',
            name='category',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
