# Generated by Django 4.2.5 on 2024-03-12 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminapi', '0003_remove_buscategory_busowner_remove_buscategory_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='busroute',
            name='busowner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='adminapi.busowner'),
        ),
        migrations.AddField(
            model_name='busroutestops',
            name='busowner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='adminapi.busowner'),
        ),
        migrations.AddField(
            model_name='busstoptime',
            name='busowner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='adminapi.busowner'),
        ),
        migrations.AlterField(
            model_name='buscategory',
            name='category',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Bus Owner', 'Bus Owner'), ('Passenger', 'Passenger')], max_length=50),
        ),
    ]
