# Generated by Django 4.2.5 on 2024-03-12 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapi', '0004_busroute_busowner_busroutestops_busowner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus',
            name='Engine_no',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='bus',
            name='Number_plate',
            field=models.CharField(max_length=500, unique=True),
        ),
        migrations.AlterField(
            model_name='route',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
