# Generated by Django 4.2.5 on 2024-03-12 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapi', '0005_alter_bus_engine_no_alter_bus_number_plate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='busroute',
            name='routetime',
            field=models.TimeField(null=True),
        ),
    ]
