# Generated by Django 4.2.5 on 2024-03-12 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapi', '0006_busroute_routetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='busroute',
            name='routetime',
            field=models.TimeField(),
        ),
    ]
