# Generated by Django 4.2.5 on 2024-03-12 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminapi', '0007_alter_busroute_routetime'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusStopCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField()),
                ('busowner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='adminapi.busowner')),
                ('busstop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapi.busroutestops')),
            ],
        ),
    ]
