# Generated by Django 4.2.5 on 2024-03-12 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapi', '0008_busstopcost'),
    ]

    operations = [
        migrations.AddField(
            model_name='busroutestops',
            name='stop_number',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
