# Generated by Django 4.2.5 on 2024-03-12 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminapi', '0009_busroutestops_stop_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='busroute',
            name='busowner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapi.busowner'),
        ),
        migrations.AlterField(
            model_name='busroutestops',
            name='busowner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapi.busowner'),
        ),
        migrations.AlterField(
            model_name='busroutestops',
            name='stop_number',
            field=models.PositiveIntegerField(),
        ),
    ]
