# Generated by Django 4.2.5 on 2024-03-14 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapi', '0010_alter_busroute_busowner_alter_busroutestops_busowner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='busowner',
            name='is_approved',
            field=models.CharField(choices=[('Rejected', 'Rejected'), ('Pending', 'Pending'), ('Approved', 'Approved')], default='Pending', max_length=50),
        ),
    ]
