# Generated by Django 4.2.5 on 2024-03-15 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapi', '0012_alter_busowner_is_approved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bus',
            name='buscategory',
        ),
    ]
