# Generated by Django 4.2.5 on 2024-03-15 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminapi', '0013_remove_bus_buscategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusStopDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField()),
                ('amount', models.PositiveIntegerField()),
                ('busowner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='adminapi.busowner')),
            ],
        ),
        migrations.RemoveField(
            model_name='busstoptime',
            name='busowner',
        ),
        migrations.RemoveField(
            model_name='busstoptime',
            name='busstop',
        ),
        migrations.RemoveField(
            model_name='busroutestops',
            name='stop_number',
        ),
        migrations.DeleteModel(
            name='BusStopCost',
        ),
        migrations.DeleteModel(
            name='BusStopTime',
        ),
        migrations.AddField(
            model_name='busstopdetail',
            name='busstop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapi.busroutestops'),
        ),
    ]
